'''
    Pentagonal numbers are generated by the formula, P_n=n(3n−1)/2. The first ten pentagonal numbers are:
    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
    It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference, 70 - 22 = 48, is not pentagonal.
    Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal and D = |P_k - P_j| is minimised; what is the value of D?
'''

def problem_44():
    def is_pentagonal(num):
        n = int((2 * num / 3)**0.5) + 1
        return n * (3 * n - 1) / 2 == num  

    j = 1
    while True:
        j += 1
        pj = j * (3 * j - 1) // 2
        for k in range(j, 0, -1):
            pk = k * (3 * k - 1) // 2
            if is_pentagonal(pj + pk) and is_pentagonal(abs(pj - pk)):
                return abs(pj - pk)

print(problem_44())