'''
    Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    Triangle	 	T_n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
    Pentagonal	 	P_n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
    Hexagonal	 	H_n=n(2n−1)	 	1, 6, 15, 28, 45, ...
    It can be verified that T_285 = P_165 = H_143 = 40755.
    Find the next triangle number that is also pentagonal and hexagonal.
'''

def problem_45():
    def is_pentagonal(num):
        n = int((2 * num / 3)**0.5) + 1
        return n * (3 * n - 1) / 2 == num
    def is_hexagonal(num):
        n = int((num / 2)**0.5) + 1
        return n * (2 * n - 1) == num    

    t = 285
    while True:
        t += 1
        num = t * (t + 1) // 2
        if is_pentagonal(num) and is_hexagonal(num):
            return num

print(problem_45())